export const insertUsers="insert into users(role_id,user_name,email_id,password,active,created_date_and_time,update_date_and_time,`key"+"`)values(?,?,?,?,?,?,?,?)";
export const getLoginDetails="select password,user_name,id,role_id from users where `user_name`=?||`email_id`=?";
export const insertProject="insert into projects(project_name,project_version,created_by,created_on,updated_on)values(?,?,?,?,?)";
export const updtaeProject="update projects set project_name=?,project_version=?,updated_on=? where id=?";
export const deleteProject="delete from projects where id= ?";
export const getProjectsForAllDetails="SELECT projects.*,users.user_name as createdUserName FROM projects inner join users";
export const getProjectsForparticularUsrer="select id,project_name,project_version from projects where created_by =?";
export const insertUserDetails="insert into user_details(user_id,first_name,last_name,created_on,updated_on)values(?,?,?,?,?)";
export const updtaeUserDetails="update user_details set first_name=?,last_name=?,updated_on=? where user_id=?";
export const deleteUserDetails="delete from user_details where id= ?";
export const getUserDetails="select id,user_id,first_name,last_name,profile_pic from user_details where user_id=?";
export const insertUserDetailsWithProfilePic="insert into user_details(user_id,first_name,last_name,profile_pic,created_on,updated_on)values(?,?,?,?,?,?)";
export const updtaeUserDetailswithProfilePic="update user_details set first_name=?,last_name=?,profile_pic=?,updated_on=? where user_id=?";
export const deleteProjectsBasedonCreatedby="delete from projects where created_by=?";
export const deleteUser="delete from users where id=?";
export const usersCount="select count(*) as count from users where role_id=?";
export const userdrtailsCount="select count(*) as count from user_details where user_id=?";
export const getIdUsingKey="select id from users where `key`=?";
export const userActivation="update users set active=1 where id=?";
export const MontlyUserdata="SELECT users.role_id,users.id,users.email_id,users.user_name,user_details.first_name,user_details.last_name,users.created_date_and_time from users left join user_details on users.id=user_details.user_id where users.created_date_and_time<=? AND users.created_date_and_time>=?";
export const getProjectsForAllDetailsforuser="SELECT projects.*,users.user_name as createdUserName FROM projects inner join users where users.id=?";