export const WIDGETNAME = "widgetName";
export const VALUE = "value";
export const XPATH = "xpath";
export const ACTION = "action";
export const XPOS = "position_X";
export const YPOS = "position_Y";
export const VALIDATE = "validate";
export const ACTIVE = "active";
export const ACTIVEVALUE = "actionableEvent";
export const EXECUTE = "execute";
export const PAGEURL = "pageURL";
export const CATEGORY = "category";
export const WAITTIME = "waitTime";
export const ID = "id";
export const CLASSNAME = "className";
export const CSS = "css"; // not used for now
export const RXPATH = "xpathRelative"; // not used for now
export const STATE = "state";
export const HEIGHT = "height";
export const WIDTH = "width";
export const TAGNAME = "tagName";
export const CVTYPE = "type";
export const CVPROP = "properties"; // url, username, password, database....
export const CVRESULT = "result";
export const CVMATCH = "match";
export const CVACTION = "action";
export const CVVALIDATE = "validate";
export const MISC = "misc"; // pageURL, x, y, category, waitTime
export const DYNAMIC = "dynamicControl"; // check, type, link, searchTerm/key